import { haversine } from '../utils/coordinateUtils';
import { ROUTE_ANALYSIS as C } from '../config/routeAnalysisConfig';
const cache=new Map();
const total=(points)=>points.slice(1).reduce((s,p,i)=>s+haversine(points[i],p),0);
const swap=(points,i,j)=>{const copy=[...points];[copy[i],copy[j]]=[copy[j],copy[i]];return copy};
export function optimizeVisits(visits,endpoints=null){
  const pointsFor=(items)=>items.map(v=>v.start||v.end).filter(Boolean);
  if(!endpoints||(!endpoints.startPoint&&!endpoints.endPoint)){if(visits.length<4)return visits;const [start,...rest]=visits;const ordered=[start];while(rest.length){let best=0,bestKm=Infinity;rest.forEach((v,i)=>{const km=haversine(ordered.at(-1).start||ordered.at(-1).end,v.start||v.end);if(km<bestKm){bestKm=km;best=i}});ordered.push(rest.splice(best,1)[0])}let changed=true;while(changed){changed=false;for(let i=1;i<ordered.length-2;i++)for(let j=i+1;j<ordered.length-1;j++){const candidate=[...ordered.slice(0,i),...ordered.slice(i,j+1).reverse(),...ordered.slice(j+1)];const a=total(pointsFor(ordered)),b=total(pointsFor(candidate));if(b<a*.995){ordered.splice(0,ordered.length,...candidate);changed=true}}}return ordered}
  const rest=visits.slice(), ordered=[]; let cursor=endpoints.startPoint||pointsFor(rest)[0];
  while(rest.length){let best=0,bestKm=Infinity;rest.forEach((v,i)=>{const point=v.start||v.end;const km=cursor&&point?haversine(cursor,point):Infinity;if(km<bestKm){bestKm=km;best=i}});const next=rest.splice(best,1)[0];ordered.push(next);cursor=next.start||next.end}
  return improve(ordered,endpoints);
}
function improve(ordered,endpoints){
  if(ordered.length<3)return ordered;
  const score=(items)=>{const points=[...(endpoints?.startPoint?[endpoints.startPoint]:[]),...items.map(v=>v.start||v.end).filter(Boolean),...(endpoints?.endPoint?[endpoints.endPoint]:[])];return total(points)};
  let changed=true;while(changed){changed=false;for(let i=endpoints?.startPoint?0:1;i<ordered.length-1;i++)for(let j=i+1;j<ordered.length;j++){const candidate=[...ordered.slice(0,i),...ordered.slice(i,j+1).reverse(),...ordered.slice(j+1)];if(score(candidate)<score(ordered)*.995){ordered.splice(0,ordered.length,...candidate);changed=true}}}return ordered
}
function crossings(points){let changes=0;for(let i=2;i<points.length;i++){const a=points[i-2],b=points[i-1],c=points[i];const ab=[b[0]-a[0],b[1]-a[1]],bc=[c[0]-b[0],c[1]-b[1]];if(ab[0]*bc[0]+ab[1]*bc[1]<0)changes++}return changes}
export function analyzeRoute(visits,actualKm,suggestedKm,endpoints=null){const endpointKey=endpoints?`${endpoints.startPoint?.join(',')||''}:${endpoints.endPoint?.join(',')||''}`:'';const key=`${visits.map(v=>v.id).join('|')}:${actualKm||0}:${suggestedKm||'local'}:${endpointKey}`;if(cache.has(key))return cache.get(key);const inner=visits.map(v=>v.start||v.end).filter(Boolean);const points=[...(endpoints?.startPoint?[endpoints.startPoint]:[]),...inner,...(endpoints?.endPoint?[endpoints.endPoint]:[])];const suggestedVisits=optimizeVisits(visits,endpoints);const suggestedPoints=[...(endpoints?.startPoint?[endpoints.startPoint]:[]),...suggestedVisits.map(v=>v.start||v.end).filter(Boolean),...(endpoints?.endPoint?[endpoints.endPoint]:[])];const baseline=Math.max(suggestedKm??total(suggestedPoints),.01);const actual=actualKm??total(points);const saving=Math.max(0,actual-baseline),efficiency=Math.min(100,baseline/Math.max(actual,.01)*100),reversals=crossings(points);const ratio=actual/baseline;const quality=ratio<=C.goodMultiplier?'GOOD':ratio<=C.averageMultiplier?'AVERAGE':'BELOW AVERAGE';const pattern=reversals<=1&&ratio<=1.15?'STRAIGHT / COHERENT':reversals>=Math.max(2,points.length/3)||ratio>1.25?'ZIG-ZAG / BACKTRACKING':'MIXED';const meaningful=saving>=C.meaningfulSavingKm&&saving/actual*100>=C.meaningfulSavingPercent;const explanation=quality==='GOOD'?'Current route is already relatively efficient. Only minor improvement was detected.':quality==='AVERAGE'?'Some direction reversals were detected. A more geographically ordered sequence could reduce travel distance.':'Several nearby visits were handled in a non-sequential order. Grouping nearby visits before moving to the next area could reduce travel distance.';const result={quality,pattern,actualKm:actual,suggestedKm:baseline,saving,efficiency,reversals,backtracking:reversals>=3?'High':reversals>=1?'Moderate':'Low',suggestedVisits,suggestedPoints,meaningful,explanation};cache.set(key,result);return result}
