import React, { useEffect, useMemo, useState } from 'react';
import { calculateJointWorkingKpis, KPI_BUCKETS, prepareJointWorkingRows } from '../services/jointWorkingKpi';
import { csvValue } from '../utils/formatUtils';

const monthLabel = (key) => {
  if (!key) return '';
  const [year, month] = key.split('-').map(Number);
  return new Intl.DateTimeFormat('en-IN', { month: 'long', year: 'numeric' }).format(new Date(year, month - 1, 1));
};

function BreakdownTable({ title, rows, columns }) {
  return <section className="joint-debug-section"><h4>{title} <small>({rows.length.toLocaleString()} groups)</small></h4><div className="joint-debug-scroll"><table className="joint-debug-table"><thead><tr>{columns.map(({ label }) => <th key={label}>{label}</th>)}</tr></thead><tbody>{rows.map((row, index) => <tr key={`${title}-${index}`}>{columns.map(({ key }) => <td key={key}>{typeof row[key] === 'boolean' ? (row[key] ? 'Yes' : 'No') : row[key]}</td>)}</tr>)}</tbody></table></div></section>;
}

export default function JointWorkingKpi({ report }) {
  const prepared = useMemo(() => prepareJointWorkingRows(report?.records || []), [report]);
  const [monthOverride, setMonthOverride] = useState('');
  const months = prepared.months;
  useEffect(() => setMonthOverride(''), [report]);
  const selectedMonth = months.includes(monthOverride) ? monthOverride : (months.at(-1) || '');
  const result = useMemo(() => selectedMonth ? calculateJointWorkingKpis(prepared, selectedMonth) : null, [prepared, selectedMonth]);
  const [showDetails, setShowDetails] = useState(false);
  useEffect(() => {
    if (result) console.info('[Joint Working KPI] Selected-month raw calculation audit', { selectedMonth, ...result.details });
  }, [result, selectedMonth]);

  const exportCsv = () => {
    if (!result) return;
    const rows = [
      ['Month', 'KPI', ...KPI_BUCKETS.map(({ label }) => label)],
      [monthLabel(selectedMonth), 'Q.1 TOTAL NO. OF VISIT DAYS OF JOINT WORKING (BDO WITH SENIOR PERSON)', ...KPI_BUCKETS.map(({ key }) => result.values.q1[key])],
      [monthLabel(selectedMonth), 'Q.2 NO. OF RETAILER VISITED, BDO WITH SENIOR SALES PERSON', ...KPI_BUCKETS.map(({ key }) => result.values.q2[key])],
      [monthLabel(selectedMonth), 'Q.3 NO. OF DISTRIBUTOR VISITED, PHYSICALLY BY SENIOR PERSON (UNIQUE NUMBER)', ...KPI_BUCKETS.map(({ key }) => result.values.q3[key])],
    ];
    const csv = rows.map((row) => row.map(csvValue).join(',')).join('\n');
    const url = URL.createObjectURL(new Blob([csv], { type: 'text/csv;charset=utf-8' }));
    const anchor = document.createElement('a');
    anchor.href = url;
    anchor.download = `joint-working-kpi-${selectedMonth}.csv`;
    anchor.click();
    URL.revokeObjectURL(url);
  };

  return <main className="joint-kpi">
    <section className="joint-kpi-heading">
      <div><span className="eyebrow">CHECK-IN REPORT · JOINT WORKING</span><h2>JOINT WORKING KPI DASHBOARD</h2><p>Calculated from the currently loaded Check-In report.</p></div>
      <div className="joint-kpi-controls"><div><label htmlFor="joint-kpi-month">Month</label><select id="joint-kpi-month" value={selectedMonth} disabled={!months.length} onChange={(event) => setMonthOverride(event.target.value)}>{months.map((month) => <option key={month} value={month}>{monthLabel(month)}</option>)}</select></div><button className="secondary" disabled={!result} onClick={exportCsv}>Export Joint Working KPI</button></div>
    </section>
    {!report && <section className="card joint-kpi-empty"><h3>Upload a Check-In Report to view this dashboard</h3><p>This report automatically uses the same Check-In data as the main dashboard.</p></section>}
    {report && !months.length && <section className="card joint-kpi-empty"><h3>No valid visit dates found</h3><p>Upload a Check-In file with dates in the Date column.</p></section>}
    {result && <>
      <section className="card joint-kpi-table-wrap"><div className="joint-kpi-title">JOINT WORKING KPI DASHBOARD <span>{monthLabel(selectedMonth)}</span></div><div className="table-scroll joint-kpi-scroll"><table className="joint-kpi-table"><thead><tr><th className="q-cell" aria-label="Question"/><th className="metric-cell">Metric</th>{KPI_BUCKETS.map((bucket) => <th key={bucket.key} className={`${bucket.key === 'firstHalf' || bucket.key === 'secondHalf' ? 'half-cell' : ''}`}>{bucket.label}</th>)}</tr></thead><tbody>
        <tr><th className="q-cell">Q.1</th><th className="metric-cell">TOTAL NO. OF VISIT DAYS OF JOINT WORKING (BDO WITH SENIOR PERSON)</th>{KPI_BUCKETS.map(({ key }) => <td key={key}>{result.values.q1[key].toLocaleString()}</td>)}</tr>
        <tr><th className="q-cell">Q.2</th><th className="metric-cell">NO. OF RETAILER VISITED, BDO WITH SENIOR SALES PERSON</th>{KPI_BUCKETS.map(({ key }) => <td key={key}>{result.values.q2[key].toLocaleString()}</td>)}</tr>
        <tr><th className="q-cell">Q.3</th><th className="metric-cell">NO. OF DISTRIBUTOR VISITED, PHYSICALLY BY SENIOR PERSON (UNIQUE NUMBER)</th>{KPI_BUCKETS.map(({ key }) => <td key={key}>{result.values.q3[key].toLocaleString()}</td>)}</tr>
      </tbody></table></div></section>
      <section className="joint-kpi-detail-toggle"><button className="secondary" aria-expanded={showDetails} onClick={() => setShowDetails((value) => !value)}>{showDetails ? 'Hide Calculation Details' : 'View Calculation Details'}</button></section>
      {showDetails && <section className="card joint-kpi-details"><div className="section-head"><div><span className="eyebrow">CALCULATION TRANSPARENCY</span><h3>{monthLabel(selectedMonth)} details</h3></div></div><div className="joint-debug-reconcile"><b>Q2 reconciliation:</b> {result.details.totalMonthRows.toLocaleString()} selected-month rows → {result.details.yesRows.toLocaleString()} Joint Working YES → {result.details.q2SeniorRows.toLocaleString()} approved Manager Sales User Designations → {result.details.q2JuniorRows.toLocaleString()} approved Executive/BDO Joint Working Designations → {result.details.q2NamedRoleRows.toLocaleString()} with Joint Working Name → {result.details.q2QualifyingRows.toLocaleString()} DEALER/OTHER rows. <b>Q2 = {result.details.q2Dealer.toLocaleString()} Dealer + {result.details.q2Other.toLocaleString()} Other.</b><br/><b>Q1 audit:</b> {result.details.q1QualifyingRows.toLocaleString()} qualifying Manager + BDO rows → {result.details.q1UniqueManagerDateCount.toLocaleString()} unique Manager (Sales User Name + Emp ID) + Date pairs. The Manager + name rows total {result.details.q1SeniorNameDayCeiling.toLocaleString()} unique pairs before checking the Executive/BDO designation; {result.details.q1JuniorDesignationExcludedRows.length.toLocaleString()} rows fail that designation check. {result.details.q2TypeExcludedRows.toLocaleString()} otherwise qualifying joint-work rows have a Type outside DEALER/OTHER.</div><div className="joint-detail-grid"><article><h4>Q.1 · Unique Manager + Date</h4><p>Qualifying source rows: <b>{result.details.q1QualifyingRows.toLocaleString()}</b></p><p>Unique Manager + Date: <b>{result.details.q1UniqueManagerDateCount.toLocaleString()}</b></p><div className="joint-senior-list">{KPI_BUCKETS.map((bucket) => <section className="joint-type-bucket" key={bucket.key}><h5>{bucket.label} · Q1 total {result.values.q1[bucket.key].toLocaleString()}</h5>{result.details.q1BySeniorByBucket[bucket.key].map(({ senior, date, rawRows, count }) => <div key={`${bucket.key}-${senior}-${date}`}><span>{senior}<small>{date} · {rawRows} raw row(s)</small></span><b>{count}</b></div>)}{!result.details.q1BySeniorByBucket[bucket.key].length && <small>No qualifying visit days.</small>}</section>)}</div></article><article><h4>Q.2 · Retailer visits</h4><p>DEALER rows: <b>{result.details.q2Dealer.toLocaleString()}</b></p><p>OTHER rows: <b>{result.details.q2Other.toLocaleString()}</b></p><p>TOTAL: <b>{result.details.q2QualifyingRows.toLocaleString()}</b></p>{result.details.q2ExclusionReasons.map(({ reason, count }) => <p key={reason}>{reason}: <b>{count.toLocaleString()}</b></p>)}</article><article><h4>Q.3 · Distributor visits</h4><p>Total qualifying rows: <b>{result.details.q3QualifyingRows.toLocaleString()}</b></p><p>Unique distributor count (1-15TH): <b>{result.values.q3.firstHalf.toLocaleString()}</b></p></article></div>
        <details className="joint-debug-disclosure"><summary>Show all {result.details.q2ByDesignationTypeSenior.length.toLocaleString()} qualifying-name designation/type groups</summary><BreakdownTable title="Joint Working = YES + name + Dealer/Other" rows={result.details.q2ByDesignationTypeSenior} columns={[{ key: 'designation', label: 'Sales User Designation' }, { key: 'jointWorkingDesignation', label: 'Joint Working Designation' }, { key: 'designationSalesType', label: 'Designation Sales Type' }, { key: 'type', label: 'Type' }, { key: 'senior', label: 'Joint Working Name / BDO' }, { key: 'count', label: 'Rows' }, { key: 'juniorDesignation', label: 'Approved roles' }]} /></details>
        <details className="joint-debug-disclosure"><summary>Show all {result.details.excludedQ2Rows.length.toLocaleString()} Joint Working YES rows excluded from Q2</summary><BreakdownTable title="Excluded Q2 rows with the exact failed condition" rows={result.details.excludedQ2Rows} columns={[{ key: 'date', label: 'Date' }, { key: 'employee', label: 'Sales User / Manager' }, { key: 'empId', label: 'Emp ID' }, { key: 'designation', label: 'Sales User Designation' }, { key: 'jointWorkingDesignation', label: 'Joint Working Designation / BDO' }, { key: 'designationSalesType', label: 'Designation Sales Type' }, { key: 'type', label: 'Type' }, { key: 'jointWorking', label: 'Joint Working' }, { key: 'senior', label: 'Joint Working Name' }, { key: 'company', label: 'Company / Partner' }, { key: 'reason', label: 'Why excluded' }]} /></details>
        <details className="joint-debug-disclosure"><summary>Show {result.details.q1JuniorDesignationExcludedRows.length.toLocaleString()} Q1 rows excluded by the companion Junior/BDO designation rule</summary><BreakdownTable title="Q1 rows with an approved Senior but unapproved Joint Working Designation" rows={result.details.q1JuniorDesignationExcludedRows} columns={[{ key: 'date', label: 'Date' }, { key: 'employee', label: 'Sales User / Manager' }, { key: 'empId', label: 'Emp ID' }, { key: 'designation', label: 'Manager Designation' }, { key: 'jointWorking', label: 'Joint Working' }, { key: 'senior', label: 'Joint Working Name' }, { key: 'jointWorkingDesignation', label: 'Joint Working Designation' }, { key: 'type', label: 'Type' }, { key: 'reason', label: 'Why excluded' }]} /></details>
        <details className="joint-debug-disclosure"><summary>Show Q1 per-Manager subtotal (G-column method)</summary>{KPI_BUCKETS.map((bucket) => <section className="joint-debug-section" key={bucket.key}><h4>{bucket.label} · subtotal {result.values.q1[bucket.key].toLocaleString()}</h4><BreakdownTable title="Manager qualifying visits and distinct days" rows={result.details.q1ManagerSummariesByBucket[bucket.key]} columns={[{ key: 'manager', label: 'Manager' }, { key: 'empId', label: 'Emp ID' }, { key: 'qualifyingRows', label: 'Qualifying check-ins' }, { key: 'visitDays', label: 'Distinct visit days (G)' }, { key: 'dates', label: 'Dates counted' }]} /></section>)}</details>
        <details className="joint-debug-disclosure"><summary>Show Q1 Manager + Date set calculation by bucket</summary>{KPI_BUCKETS.map((bucket) => <BreakdownTable key={bucket.key} title={`${bucket.label} · ${result.values.q1[bucket.key]} unique manager/date pairs`} rows={result.details.q1BySeniorByBucket[bucket.key]} columns={[{ key: 'senior', label: 'Manager (Sales User Name)' }, { key: 'empId', label: 'Emp ID' }, { key: 'date', label: 'Date' }, { key: 'rawRows', label: 'Qualifying rows' }, { key: 'count', label: 'Q1 counted as' }]} />)}</details>
        <details className="joint-debug-disclosure"><summary>Show Q3 unique distributor Set calculation by bucket</summary>{KPI_BUCKETS.map((bucket) => <BreakdownTable key={bucket.key} title={`${bucket.label} · ${result.values.q3[bucket.key]} unique distributor(s)`} rows={result.details.q3UniqueByBucket[bucket.key]} columns={[{ key: 'senior', label: 'Senior Sales User' }, { key: 'designation', label: 'Designation' }, { key: 'identifier', label: 'Distributor Identifier' }, { key: 'type', label: 'Type' }, { key: 'rawRows', label: 'Rows mapped to Set entry' }]} />)}</details>
        <details className="joint-debug-disclosure"><summary>Show raw selected-month breakdowns</summary><BreakdownTable title="Joint Working = YES · Sales User Designation" rows={result.details.rawBreakdowns.designations} columns={[{ key: 'label', label: 'Sales User Designation' }, { key: 'count', label: 'Rows' }]} /><BreakdownTable title="Joint Working = YES · Joint Working Designation" rows={result.details.rawBreakdowns.jointWorkingDesignations} columns={[{ key: 'label', label: 'Joint Working Designation' }, { key: 'count', label: 'Rows' }]} /><BreakdownTable title="Joint Working = YES · Joint Working Name" rows={result.details.rawBreakdowns.jointWorkingNames} columns={[{ key: 'label', label: 'Joint Working Name / BDO' }, { key: 'count', label: 'Rows' }]} /><BreakdownTable title="Selected-month Type" rows={result.details.rawBreakdowns.types} columns={[{ key: 'label', label: 'Type' }, { key: 'count', label: 'Rows' }]} /><BreakdownTable title="Designation + Joint Working + Type" rows={result.details.rawBreakdowns.designationJointType} columns={[{ key: 'label', label: 'Designation | Joint Working | Type' }, { key: 'count', label: 'Rows' }]} /><BreakdownTable title="Joint Working Name + Type" rows={result.details.rawBreakdowns.seniorType} columns={[{ key: 'label', label: 'Joint Working Name + Type' }, { key: 'count', label: 'Rows' }]} /></details>
      </section>}
      <p className="joint-kpi-footnote">Q.1 counts unique Manager + Date Joint Working days. Q.2 counts all qualifying DEALER + OTHER Check-In rows. Q.3 counts unique Channel Partner/Distributor visits by Senior.</p>
    </>}
  </main>;
}
