import React, { useEffect, useMemo, useState } from 'react';
import { displayTime } from '../utils/dateUtils';
import { csvValue, formatDistance, num } from '../utils/formatUtils';
import { calculateRouteMetrics } from '../services/routingService';
import { buildDailyTour, TOUR_DEFAULTS } from '../services/tourPlanningService';
import { haversine } from '../utils/coordinateUtils';
import { inferAttendanceBase } from '../services/baseInference';
import { createMonthlyPlan } from '../services/monthlyTourPlanner';
import MapView from './MapView';

const planKey = (empId, date) => `tour-plan:${empId}|${date}`;
const localToday = new Date();
const today = `${localToday.getFullYear()}-${String(localToday.getMonth() + 1).padStart(2, '0')}-${String(localToday.getDate()).padStart(2, '0')}`;
const planDate = (value) => String(value || '').split('-').reverse().join('-');
const mapVisit = (dealer, distanceFromPreviousKm, distanceFromPreviousLabel) => ({ id: dealer.id, start: dealer.point, companyName: dealer.companyName || dealer.customerName, checkInLocation: dealer.address, accountCode: dealer.accountCode, channelPartner: dealer.channelPartner, beat: dealer.beat, distanceFromPreviousKm, distanceFromPreviousLabel, salesUserName: '', empId: '', durationMinutes: 0, basicOrderValue: 0 });

export default function TourPlan({ dealers, report, attendance }) {
  const employees = useMemo(() => Object.entries(dealers?.indexes?.byEmployeeId || {}).map(([empId, list]) => ({ empId, label: list[0]?.assignedSalesUsers || `Employee ${empId}`, count: list.length })).sort((a, b) => a.empId.localeCompare(b.empId)), [dealers]);
  const [empId, setEmpId] = useState(''); const [date, setDate] = useState(today); const [maxVisits, setMaxVisits] = useState(20); const [beat, setBeat] = useState('');
  const [plan, setPlan] = useState(null); const [route, setRoute] = useState(null); const [loading, setLoading] = useState(false); const [radius, setRadius] = useState(500); const [longSegmentKm, setLongSegmentKm] = useState(TOUR_DEFAULTS.longSegmentKm); const [dailyTravelLimitKm, setDailyTravelLimitKm] = useState(100); const [clusterRadiusKm, setClusterRadiusKm] = useState(TOUR_DEFAULTS.clusterRadiusKm); const [outlierKm, setOutlierKm] = useState(TOUR_DEFAULTS.outlierKm);
  const [month, setMonth] = useState(today.slice(0, 7)); const [monthlyPlan, setMonthlyPlan] = useState(null);
  const allAssigned = useMemo(() => dealers?.indexes?.byEmployeeId?.[empId] || [], [dealers, empId]);
  const assigned = useMemo(() => allAssigned.filter((dealer) => !beat || dealer.beat === beat), [allAssigned, beat]);
  const beats = useMemo(() => [...new Set(allAssigned.map((dealer) => dealer.beat).filter(Boolean))].sort(), [allAssigned]);
  const actualVisits = useMemo(() => report?.indexes?.byEmployeeDate?.[`${empId}|${date}`]?.map((id) => report.records[id]).filter((visit) => visit.start).sort((a, b) => (a.checkIn?.getTime() || 0) - (b.checkIn?.getTime() || 0)) || [], [report, empId, date]);
  const attendanceDay = attendance?.byEmployeeDate?.[`${empId}|${date}`]?.[0] || null;
  const inferredBase = useMemo(() => inferAttendanceBase(attendance, empId), [attendance, empId]);

  useEffect(() => { try { const saved = JSON.parse(localStorage.getItem(planKey(empId, date)) || 'null'); setPlan(saved?.version >= 2 ? saved : null); } catch { setPlan(null); } setRoute(null); }, [empId, date]);
  const routingPoints = useMemo(() => { if (!plan?.visits?.length) return []; const visits = plan.visits.map((visit) => visit.point); return plan.base?.point ? [plan.base.point, ...visits, plan.base.point] : visits; }, [plan]);
  useEffect(() => { let open = true; if (!routingPoints.length) return undefined; setLoading(true); calculateRouteMetrics(routingPoints).then((value) => open && setRoute(value)).finally(() => open && setLoading(false)); return () => { open = false; }; }, [routingPoints]);
  useEffect(() => { if (!plan || !route || !Number.isFinite(route.totalKm) || plan.expectedKm === route.totalKm) return; const next = { ...plan, expectedKm: route.totalKm, expectedKmSource: route.routingStatus, expectedSegmentKm: route.segmentDistances, expectedKmCalculatedAt: new Date().toISOString() }; setPlan(next); localStorage.setItem(planKey(empId, date), JSON.stringify(next)); }, [route]);
  const save = (next) => { setPlan(next); localStorage.setItem(planKey(empId, date), JSON.stringify(next)); };
  const generate = async () => { setLoading(true); try { const result = await buildDailyTour(assigned, maxVisits, { longSegmentKm, clusterRadiusKm, outlierKm, base: inferredBase, dailyTravelLimitKm }); save({ version: 3, empId, date, status: 'GENERATED', visits: result.visits, candidatePool: result.candidatePool, metrics: result.metrics, base: inferredBase, debug: result.debug, generatedAt: new Date().toISOString() }); } finally { setLoading(false); } };
  const selectMonthDay = (day, source = monthlyPlan) => { const visits = source?.days?.[day]?.visits || []; const next = { version: 3, empId, date: day, status: source?.days?.[day]?.status || 'GENERATED', visits, candidatePool: visits, base: source?.base || null, metrics: { assigned: source?.summary?.assigned || 0, valid: source?.summary?.planned || 0, invalid: source?.summary?.invalidGps || 0, clusterDealers: visits.length, outliers: 0, primaryMarket: visits[0]?.city || 'Monthly allocation', district: visits[0]?.district || '—', state: visits[0]?.state || '—', channelPartners: [...new Set(visits.map((item) => item.channelPartner).filter(Boolean))], geographicSpreadKm: 0, reason: 'Allocated once in the selected monthly plan.' }, generatedAt: source?.generatedAt || new Date().toISOString() }; localStorage.setItem(planKey(empId, day), JSON.stringify(next)); setPlan(next); setDate(day); };
  const generateMonthly = async () => { setLoading(true); try { const result = await createMonthlyPlan(assigned, month, maxVisits, inferredBase, [1,2,3,4,5,6], dailyTravelLimitKm); result.empId = empId; result.generatedAt = new Date().toISOString(); setMonthlyPlan(result); localStorage.setItem(`monthly-tour-plan:${empId}|${month}`, JSON.stringify(result)); const first = Object.values(result.days).find((day) => day.visits.length); if (first) selectMonthDay(first.date, result); } finally { setLoading(false); } };
  const reorder = (index, direction) => { if (!plan || plan.status === 'LOCKED') return; const visits = [...plan.visits]; const target = index + direction; if (target < 0 || target >= visits.length) return; [visits[index], visits[target]] = [visits[target], visits[index]]; save({ ...plan, visits, status: 'EDITED' }); };
  const approve = () => plan && save({ ...plan, status: 'APPROVED', approvedAt: new Date().toISOString() });
  const lock = () => plan && save({ ...plan, status: 'LOCKED', lockedAt: new Date().toISOString() });
  const keepAnyway = () => plan && save({ ...plan, routeReviewAccepted: true, reviewedAt: new Date().toISOString() });
  const replaceWorstStop = async () => {
    if (!plan?.candidatePool?.length || plan.status === 'LOCKED') return;
    const points = [...(plan.base?.point ? [plan.base.point] : []), ...plan.visits.map((item) => item.point), ...(plan.base?.point ? [plan.base.point] : [])];
    const metrics = await calculateRouteMetrics(points); const segments = metrics.segmentDistances;
    const segmentIndex = segments.indexOf(Math.max(...segments)); const replaceAt = Math.min(plan.visits.length - 1, Math.max(0, segmentIndex + (plan.base?.point ? 0 : 1)));
    const used = new Set(plan.visits.map((dealer) => dealer.id)); const previous = replaceAt === 0 ? plan.base : plan.visits[replaceAt - 1]; const next = plan.visits[replaceAt + 1];
    const options = plan.candidatePool.filter((dealer) => !used.has(dealer.id)).sort((a, b) => {
      const score = (dealer) => (previous?.point ? haversine(previous.point, dealer.point) : 0) + (next ? haversine(dealer.point, next.point) : 0);
      return score(a) - score(b) || String(a.id).localeCompare(String(b.id));
    });
    let replacement = null; const visits = [...plan.visits];
    for (const candidate of options) { const proposed = [...visits]; proposed[replaceAt] = candidate; const trialPoints = [...(plan.base?.point ? [plan.base.point] : []), ...proposed.map((item) => item.point), ...(plan.base?.point ? [plan.base.point] : [])]; const measured = await calculateRouteMetrics(trialPoints); if (Number.isFinite(measured.totalKm) && measured.totalKm <= dailyTravelLimitKm) { replacement = candidate; break; } }
    if (!replacement) return;
    visits[replaceAt] = replacement;
    save({ ...plan, visits, status: 'EDITED', routeReviewAccepted: false, replacedAt: new Date().toISOString() });
  };
  const routeMetrics = useMemo(() => {
    const segments = route?.segmentDistances || []; const hasBase = Boolean(plan?.base?.point);
    const visitSegments = plan?.visits?.map((_, index) => hasBase ? segments[index] : (index === 0 ? null : segments[index - 1])) || [];
    const cumulative = visitSegments.map((_, index) => hasBase ? route?.cumulativeDistances?.[index] : (index ? route?.cumulativeDistances?.[index - 1] : 0));
    const validSegments = segments.filter((value) => Number.isFinite(value)); const max = Math.max(0, ...validSegments); const total = route?.totalKm ?? null; const average = plan?.visits?.length && Number.isFinite(total) ? total / plan.visits.length : null;
    return { segments, visitSegments, cumulative, total, average, max, status: max > longSegmentKm || (Number.isFinite(total) && total > dailyTravelLimitKm) ? 'REVIEW REQUIRED' : 'COHERENT', source: route?.routingStatus || 'pending', geometry: route?.routeGeometry || [] };
  }, [plan, route, longSegmentKm, dailyTravelLimitKm]);
  const comparison = useMemo(() => { if (!plan) return null; const remaining = new Set(plan.visits.map((dealer) => dealer.id)); let completed = 0; const extras = []; actualVisits.forEach((visit) => { let match = null; let km = Infinity; plan.visits.forEach((dealer) => { const distance = haversine(visit.start, dealer.point); if (distance < km) { km = distance; match = dealer; } }); if (match && km * 1000 <= radius && remaining.has(match.id)) { remaining.delete(match.id); completed += 1; } else extras.push(visit); }); return { completed, missed: remaining.size, extra: extras.length, similarity: plan.visits.length ? (completed / plan.visits.length) * 100 : 0 }; }, [plan, actualVisits, radius]);
  const downloadCsv = (rows, filename) => { const link = document.createElement('a'); link.href = URL.createObjectURL(new Blob([rows.map((row) => row.map(csvValue).join(',')).join('\n')], { type: 'text/csv;charset=utf-8' })); link.download = filename; link.click(); URL.revokeObjectURL(link.href); };
  const exportMonthly = async () => { if (!monthlyPlan) return; const rows = [['Date','Employee','Emp ID','Sequence','Dealer/Customer','Assigned Channel Partner','Latitude','Longitude','Start Base','Distance From Previous','Cumulative KM','Expected Daily KM','Maximum Daily KM','Visit Number','Plan Status','Actual Check-In','Actual Check-Out','Actual Visit','Actual KM','Plan Followed','Deviation','Remarks']]; for (const day of Object.values(monthlyPlan.days)) { const visits = day.visits || []; const points = [...(monthlyPlan.base?.point ? [monthlyPlan.base.point] : []), ...visits.map((item) => item.point), ...(monthlyPlan.base?.point ? [monthlyPlan.base.point] : [])]; const metrics = await calculateRouteMetrics(points); const hasBase = Boolean(monthlyPlan.base?.point); let cumulative = 0; const actual = report?.indexes?.byEmployeeDate?.[`${empId}|${day.date}`]?.map((id) => report.records[id]).filter((visit) => visit.start) || []; for (let index = 0; index < visits.length; index += 1) { const dealer = visits[index]; const segment = metrics.segmentDistances[hasBase ? index : index - 1]; if (Number.isFinite(segment)) cumulative += segment; let match = null; let nearest = Infinity; actual.forEach((visit) => { const distance = haversine(visit.start, dealer.point); if (Number.isFinite(distance) && distance < nearest) { nearest = distance; match = visit; } }); const followed = match && nearest * 1000 <= radius; rows.push([planDate(day.date), employees.find((employee) => employee.empId === empId)?.label || '', empId, index + 1, dealer.companyName || dealer.customerName, dealer.channelPartner || '', dealer.point?.[0] ?? '', dealer.point?.[1] ?? '', monthlyPlan.base?.label || 'N/A', Number.isFinite(segment) ? segment : 'N/A', Number.isFinite(segment) ? cumulative : 'N/A', day.expectedKm ?? 'N/A', monthlyPlan.dailyTravelLimitKm, index + 1, day.status, followed ? displayTime(match.checkIn) : '', followed ? displayTime(match.checkOut) : '', followed ? 'Visited' : 'Missed', 'N/A', followed ? 'Yes' : 'No', followed ? '' : 'Planned visit not matched', followed ? '' : 'No matching actual check-in']); } } downloadCsv(rows, `monthly-tour-plan-${empId}-${month}.csv`); };
  const exportReport = () => { if (!plan) return; const rows = [['Date', 'Employee ID', 'Planned Customer', 'Account Code', 'Channel Partner', 'Beat', 'Planned Sequence', 'Expected KM', 'Expected Distance From Previous (KM)', 'Cumulative KM', 'Actual Check-In Time', 'Distance From Planned Location (m)', 'Visit Status', 'Plan Status'], ...plan.visits.map((dealer, index) => { let match = null; let km = Infinity; actualVisits.forEach((visit) => { const distance = haversine(visit.start, dealer.point); if (Number.isFinite(distance) && distance < km) { km = distance; match = visit; } }); const matched = match && km * 1000 <= radius; return [planDate(date), empId, dealer.companyName || dealer.customerName, dealer.accountCode, dealer.channelPartner, dealer.beat, index + 1, plan.expectedKm ?? '', routeMetrics.visitSegments[index] ?? 'N/A — GPS unavailable', routeMetrics.cumulative[index] ?? 'N/A — GPS unavailable', matched ? displayTime(match.checkIn) : '', Number.isFinite(km) ? num(km * 1000, 0) : 'N/A — GPS unavailable', matched ? 'COMPLETED AS PLANNED' : 'MISSED', plan.status]; })]; downloadCsv(rows, `tour-plan-report-${empId}-${date}.csv`); };
  const exportCustomerPlan = () => plan && downloadCsv([['User Name', 'User Code', 'Customer Type', 'Company Name', 'Customer Code', 'Mobile', 'Address', 'Last Checkin Date', 'Plan Date(dd-mm-yyyy)'], ...plan.visits.map((dealer) => [dealer.assignedSalesUsers, empId, dealer.customerType, dealer.companyName || dealer.customerName, dealer.accountCode, dealer.mobile, dealer.address, dealer.lastVisit, planDate(date)])], `customer-plan-${empId}-${date}.csv`);
  const exportSummary = () => plan && downloadCsv([['Employee', 'Employee ID', 'Plan Date', 'Planned Visits', 'Expected KM', 'Actual KM', 'KM Variance', 'KM Variance %', 'Route Status'], [employees.find((employee) => employee.empId === empId)?.label || '', empId, planDate(date), plan.visits.length, plan.expectedKm ?? '', 'Not available', 'Not available', 'Not available', routeMetrics.status]], `tour-plan-summary-${empId}-${date}.csv`);
  if (!dealers) return <section className="notice">Upload the Direct Dealer Master first. Tour plans only use dealers assigned to the selected employee.</section>;
  const nearest = plan?.visits?.[0]; const metrics = plan?.metrics;
  const cards = plan ? [['Assigned dealers', metrics.assigned], ['Eligible dealers', metrics.valid], ['Planned visits', plan.visits.length], [routeMetrics.source === 'road' ? 'Expected km' : 'Approx. distance', route ? (Number.isFinite(routeMetrics.total) ? `${num(routeMetrics.total, 2)} km` : 'N/A') : 'Calculating…'], ['Avg km / visit', Number.isFinite(routeMetrics.average) ? `${num(routeMetrics.average, 2)} km` : 'N/A'], ['Actual visits', actualVisits.length], ['Route status', routeMetrics.status]] : [['Assigned dealers', assigned.length], ['Valid GPS dealers', assigned.filter((item) => item.point).length], ['Planned visits', 0], ['Actual visits', actualVisits.length], ['Attendance', attendanceDay ? 'Available' : 'Not uploaded']];
  return <main className="tour-plan">
    <section className="tour-header"><div><span className="eyebrow">TOUR PLAN</span><h2>Future tour planning &amp; plan vs actual</h2><p>Geographic clustering happens before optimisation; only the final daily route is sent for road-distance routing.</p></div></section>
    <section className="card tour-controls"><div><label>Employee</label><select value={empId} onChange={(event) => setEmpId(event.target.value)}><option value="">Select assigned employee</option>{employees.map((employee) => <option key={employee.empId} value={employee.empId}>{employee.empId} — {employee.label} ({employee.count} dealers)</option>)}</select></div><div><label>Plan date</label><input type="date" value={date} onChange={(event) => setDate(event.target.value)}/></div><div><label>Beat</label><select value={beat} onChange={(event) => setBeat(event.target.value)}><option value="">All assigned beats</option>{beats.map((item) => <option key={item}>{item}</option>)}</select></div><div><label>Maximum visits/day</label><select value={maxVisits} onChange={(event) => setMaxVisits(event.target.value)}>{[5, 10, 15, 20, 25, 30].map((item) => <option key={item}>{item}</option>)}</select></div><div><label>Cluster radius (km)</label><input type="number" min="1" value={clusterRadiusKm} onChange={(event) => setClusterRadiusKm(Number(event.target.value) || TOUR_DEFAULTS.clusterRadiusKm)}/></div><div><label>Outlier threshold (km)</label><input type="number" min="1" value={outlierKm} onChange={(event) => setOutlierKm(Number(event.target.value) || TOUR_DEFAULTS.outlierKm)}/></div><div><label>Maximum total travel incl. return (km)</label><input type="number" min="1" value={dailyTravelLimitKm} onChange={(event) => setDailyTravelLimitKm(Number(event.target.value) || 100)}/></div><div><label>Long segment review (km)</label><input type="number" min="1" value={longSegmentKm} onChange={(event) => setLongSegmentKm(Number(event.target.value) || TOUR_DEFAULTS.longSegmentKm)}/></div><button className="primary compact" disabled={!empId || !assigned.length} onClick={generate}>Generate Suggested Tour Plan</button></section>
    {empId && <section className="card monthly-controls"><div><label>Month</label><input type="month" value={month} onChange={(event) => setMonth(event.target.value)}/></div><button className="primary compact" disabled={loading} onClick={generateMonthly}>Generate Monthly Tour Plan</button><button className="secondary" disabled={!monthlyPlan} onClick={exportMonthly}>Export Monthly Tour Report</button><p>Allocates each unique eligible assigned customer once, subject to the daily visit and full-route KM limits.</p></section>}
    {monthlyPlan && <section className="card monthly-plan"><div className="section-head"><div><span className="eyebrow">MONTHLY TOUR PLAN</span><h2>{month}</h2><p>Assigned: {monthlyPlan.summary.assigned} · Planned: {monthlyPlan.summary.planned} · Coverage: {num(monthlyPlan.summary.coverage, 1)}% · Duplicates: {monthlyPlan.summary.duplicates} · Invalid GPS: {monthlyPlan.summary.invalidGps} · Unplanned: {monthlyPlan.summary.unplanned}</p></div></div><div className="monthly-calendar">{Object.values(monthlyPlan.days).map((day) => <button key={day.date} className={`calendar-day ${day.visits.length ? 'has-plan' : ''} ${date === day.date ? 'selected' : ''}`} onClick={() => selectMonthDay(day.date)}><b>{planDate(day.date)}</b><span>{day.visits.length ? `${day.visits.length} visits` : 'No plan'}</span><small>{day.status}</small></button>)}</div><p className="notice">Plan validation: {monthlyPlan.summary.planned} / {monthlyPlan.summary.assigned} unique customers planned; {monthlyPlan.summary.duplicates} duplicate visits; no day exceeds {monthlyPlan.maxVisits} visits.</p></section>}
    {empId && <section className="tour-kpis">{cards.map(([label, value]) => <div className="card kpi" key={label}><span>{label}</span><strong>{value}</strong></div>)}</section>}
    {plan && <><section className="card cluster-summary"><span className="eyebrow">TODAY'S ROUTE CLUSTER</span><strong>{metrics.primaryMarket}</strong><span>{metrics.district} · {metrics.state}</span><span>Dealers in cluster: {metrics.clusterDealers} · Excluded outliers: {metrics.outliers} · Invalid GPS: {metrics.invalid}</span><span>Channel partners: {metrics.channelPartners?.join(', ') || 'Not available'}</span></section>
      <section className="tour-layout"><section className="card map-card planned-map"><div className="section-head"><div><span className="eyebrow">SUGGESTED / EXPECTED TOUR PLAN</span><h2>{route ? `${routeMetrics.source === 'road' ? 'Expected KM' : 'Approx. distance'}: ${Number.isFinite(routeMetrics.total) ? num(routeMetrics.total, 2) : 'N/A'} km` : 'Calculating…'}</h2><p>Expected visits: {plan.visits.length} · Average: {Number.isFinite(routeMetrics.average) ? num(routeMetrics.average, 2) : 'N/A'} km / visit · {routeMetrics.status}. {routeMetrics.source === 'straight' ? 'Approx. straight-line distance — road routing was unavailable.' : routeMetrics.source === 'failed' || routeMetrics.source === 'invalid' ? 'Route unavailable — GPS validation failed.' : 'Actual road-distance total from the final selected sequence.'} {loading ? 'Calculating final road route…' : ''}</p></div><span className="plan-status">{plan.status}</span></div><MapView visits={plan.visits.map((dealer, index) => mapVisit(dealer, routeMetrics.visitSegments[index], formatDistance(routeMetrics.visitSegments[index], { first: index === 0 && !plan.base })))} route={{ geometry: routeMetrics.geometry }} activeIndex={-1} routeColor="#2563eb" routeLabel="Planned" specialLocations={plan.base?.point ? [{ point: plan.base.point, label: `${plan.base.label} (${plan.base.confidence})` }] : []}/></section>
        <section className="card plan-panel"><div className="section-head"><div><span className="eyebrow">DATE-WISE PLAN</span><h2>{planDate(date)}</h2><p>{plan.visits.length} visits · {routeMetrics.source === 'road' ? 'Expected KM' : 'Approx. distance'}: {route ? ` ${Number.isFinite(routeMetrics.total) ? num(routeMetrics.total, 2) : 'N/A'} km` : ' Calculating…'} · {plan.status}<br/>Start base: {plan.base ? `${plan.base.label} (${plan.base.confidence} confidence)` : 'Not configured'}</p></div></div><div className="plan-actions"><button className="secondary" disabled={plan.status === 'LOCKED' || (routeMetrics.status === 'REVIEW REQUIRED' && !plan.routeReviewAccepted)} onClick={approve}>Approve</button><button className="secondary" disabled={plan.status !== 'APPROVED'} onClick={lock}>Lock</button><button className="secondary" onClick={exportReport}>Export Tour Report</button><button className="secondary" onClick={exportCustomerPlan}>Export Customer Plan</button><button className="secondary" onClick={exportSummary}>Export Summary</button></div>{routeMetrics.status === 'REVIEW REQUIRED' && <p className="notice">⚠ Route requires review: one or more segments exceed {longSegmentKm} km. <button className="secondary" disabled={plan.status === 'LOCKED'} onClick={replaceWorstStop}>Replace with nearest dealer</button> <button className="secondary" disabled={plan.status === 'LOCKED'} onClick={keepAnyway}>Keep anyway</button></p>}<ol className="plan-list">{plan.visits.map((dealer, index) => <li key={dealer.id}><div><b>{index + 1}. {dealer.companyName || dealer.customerName}</b><small>{dealer.accountCode || 'No account code'} · {dealer.channelPartner || 'No channel partner'}<br/>{dealer.beat || 'No beat'} · {dealer.city || 'No city'} · Distance from previous: {formatDistance(routeMetrics.visitSegments[index], { first: index === 0 && !plan.base })} · Cumulative: {Number.isFinite(routeMetrics.cumulative[index]) ? `${num(routeMetrics.cumulative[index], 2)} km` : 'N/A — GPS unavailable'}</small></div><span><button disabled={plan.status === 'LOCKED'} onClick={() => reorder(index, -1)}>↑</button><button disabled={plan.status === 'LOCKED'} onClick={() => reorder(index, 1)}>↓</button></span></li>)}</ol>{plan.base && <p className="plan-return">Return to {plan.base.label}: {formatDistance(routeMetrics.segments.at(-1))}</p>}</section></section>
      <section className="tour-kpis"><div className="card kpi"><span>Nearest dealer in selected cluster</span><strong>{nearest?.companyName || nearest?.customerName || '—'}</strong><small>{nearest?.accountCode || 'No account code'} · {nearest?.channelPartner || 'No channel partner'}<br/>Start location: Not configured</small></div><div className="card kpi"><span>Route validation</span><strong>{routeMetrics.status}</strong><small>{metrics.reason}<br/>Geographic spread: {num(metrics.geographicSpreadKm, 2)} km</small></div></section>
      <details className="card tour-debug"><summary>Route generation debug</summary><pre>{JSON.stringify({ ...plan.debug, osrm: { source: routeMetrics.source, totalKm: routeMetrics.total, segmentKm: routeMetrics.segments, averageKmPerVisit: routeMetrics.average, longestSegmentKm: routeMetrics.max, status: routeMetrics.status } }, null, 2)}</pre></details>
      <section className="card plan-vs-actual"><div className="section-head"><div><span className="eyebrow">PLAN VS ACTUAL</span><h2>Tour plan followed / actual execution</h2><p>GPS matching uses a configurable {radius} metre radius; this is factual visit correspondence, not a performance score.</p></div><label>Match radius (m)<input type="number" min="50" step="50" value={radius} onChange={(event) => setRadius(Number(event.target.value) || 500)}/></label></div><div className="plan-follow-kpis"><span><b>Planned</b>{plan.visits.length}</span><span><b>Completed</b>{comparison?.completed || 0}</span><span><b>Missed</b>{comparison?.missed || 0}</span><span><b>Extra</b>{comparison?.extra || 0}</span><span><b>Sequence similarity</b>{num(comparison?.similarity || 0, 1)}%</span></div></section>
    </>}
  </main>;
}
