import React, { useRef, useState } from 'react';

function LayerUpload({ title, subtitle, accept, onFile, loading, status, progress, optional = false }) {
  const input = useRef(); const [drag, setDrag] = useState(false);
  const pick = (file) => file && onFile(file);
  return <div className={`layer-upload ${drag ? 'drag' : ''}`} onDragOver={(event) => { event.preventDefault(); setDrag(true); }} onDragLeave={() => setDrag(false)} onDrop={(event) => { event.preventDefault(); setDrag(false); pick(event.dataTransfer.files[0]); }} onClick={() => !loading && input.current.click()}>
    <input ref={input} type="file" accept={accept} hidden onChange={(event) => { const file = event.target.files[0]; event.target.value = ''; pick(file); }}/><span className="eyebrow">{optional ? 'OPTIONAL DATA LAYER' : 'PRIMARY DATA LAYER'}</span><b>{title}</b><small>{loading ? `${progress?.stage || 'Processing in background…'} ${progress?.progress ? `${progress.progress}%` : ''}` : status ? `✓ Loaded — ${status}` : subtitle}</small>{loading && <div className="progress supplemental-progress"><i style={{ width: `${progress?.progress || 4}%` }}/></div>}
  </div>;
}

export default function UploadPanel({ onFile, onAttendanceFile, onDealerFile, loading, progress, report, attendance, dealers, supplementalLoading, supplementalProgress }) {
  const input = useRef(); const [drag, setDrag] = useState(false); const choose = (file) => file && onFile(file); const selectFile = (event) => { const file = event.target.files[0]; event.target.value = ''; choose(file); };
  return <><section className="upload card"><div className="upload-copy"><span className="eyebrow">PRIVATE • BROWSER-ONLY</span><h2>Upload Check-In / Check-Out Excel</h2><p>Your file is read locally and is never uploaded to this application.</p></div><div className={`dropzone ${drag?'drag':''}`} onDragOver={e=>{e.preventDefault();setDrag(true)}} onDragLeave={()=>setDrag(false)} onDrop={e=>{e.preventDefault();setDrag(false);choose(e.dataTransfer.files[0])}} onClick={()=>!loading&&input.current.click()}><input ref={input} type="file" accept=".xlsx,.xls,.csv" hidden onChange={selectFile}/><strong>{loading ? progress.stage : 'Drop Check-In report here or browse'}</strong>{loading?<><div className="progress"><i style={{width:`${progress.progress||0}%`}}/></div><small>{progress.progress||0}% {progress.total?`· ${progress.total.toLocaleString()} rows`:''}</small></>:<small>.xlsx, .xls, or .csv</small>}</div>{report && <div className="file-info"><strong>{report.fileName}</strong><span>{report.records.length.toLocaleString()} rows</span><span>{report.indexes.employees.length} employees</span><span>{report.validGpsCount.toLocaleString()} valid GPS</span><span>{report.missingGpsCount.toLocaleString()} incomplete GPS</span></div>}</section>
    <section className="layer-upload-grid card"><LayerUpload title="Attendance Report" subtitle="Not uploaded" accept=".xlsx,.xls,.csv" onFile={onAttendanceFile} loading={supplementalLoading.attendance} progress={supplementalProgress.attendance} status={attendance && `${attendance.records.length.toLocaleString()} records · ${attendance.stats.employees} employees`} optional/><LayerUpload title="Dealer Master" subtitle="Not uploaded" accept=".xlsx,.xls,.csv" onFile={onDealerFile} loading={supplementalLoading.dealers} progress={supplementalProgress.dealers} status={dealers && `${dealers.stats.total.toLocaleString()} dealers · ${dealers.stats.validGps.toLocaleString()} valid GPS`} optional/><div className="layer-upload future"><span className="eyebrow">OPTIONAL DATA LAYER</span><b>Tour Plan Report</b><small>Not uploaded — planning will use estimated dealer route only.</small></div></section>
  </>;
}
